### ISSUE TITLE
Dockerisation du serveur DCAT

### ISSUE THREAD

**Issue by jgrosmaire** [isogeo/dcat-server#10]
**ATTENTION ! Certaines modifications nécessitent la mise à jour des variables d'environnement en SaaS**

## Comment recetter 

Pré-requis : 

* API locale
* docker + docker-compose en local
* images nécessaires téléchargées sur le [drive](https://drive.google.com/drive/folders/1WuigM83lnYSdI5wolOdbtf3Ypi5gDIFi) et charges dans docker (`docker load -i dcat-server.tar`), vérifier ensuite avec la commande (docker image ls)

Tâches : 

* Créer le `docker-compose.yml` suivant

```
version: "3.9"
services:
  geodataprocess-api:
    image: gdp-api
    ports:
      - 2000:2000
    restart: always
    environment:
      OPEN_CAT_NO_SSL: http://localhost:5000
      SERVER_URL: http://localhost:2000
    networks:
      - dev

  dcat:
    image : dcat-server
    ports:
      - 5000:5000
    restart: always
    environment:
      ISOGEO_API_URL: http://host.docker.internal:8010
      ISOGEO_TOKEN_URL: http://host.docker.internal:8020/oauth/token
      DCAT_SERVER_URL: http://localhost:5000
      ISOGEO_OPEN_URL: http://test
      ISOGEO_APP_URL: http://app
      GDP_API_URL: http://geodataprocess-api:2000
      ISOGEO_CLIENT_ID: id
      ISOGEO_CLIENT_SECRET: secret
    networks:
      - dev
      

networks:
  dev:
```

* Lancer la commande 

```
docker-compose up
```

* Tester que le serveur DCAT fonctionne correctement
